version: '3.8'
services:
  app:
    image: jaehoonman_jenkins
    container_name: jaehoonman_jenkins
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jaehoonman_db
      SPRING_DATASOURCE_USERNAME: jaehoonman
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network
  db:
    image: postgres:14
    container_name: jaehoonman_postgres
    environment:
      POSTGRES_DB: jaehoonman_db
      POSTGRES_USER: jaehoonman
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  my_pgdata:
    external: true

networks:
  app-network:
    driver: bridge


