spring:
  # ?????? ??
  application:
    name: jenkins_sample

  # ?????? ?? ??
  datasource:
    #url: jdbc:postgresql://localhost:5432/jaehoonman_db
    url: jdbc:postgresql://db:5432/jaehoonman_db
    username: jaehoonman
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update # ???? ???? ?????.
    properties:
      hibernate:
        show_sql: true # Interaction ? ???? ???? ??? ?????.
        format_sql: true # ??? ??? ????.
        use_sql_comments: true # ??? ?? ??